---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-static-config
data:
  static.yaml: |
    entryPoints:
      web:
        address: ':80'
      websecure:
        address: ':443'

    log:
      level: INFO

    api: {}

    metrics:
      prometheus:
        manualRouting: true
        buckets:
          - 0.1
          - 0.3
          - 1.2
          - 5.0
          - 10.0

    forwardingTimeouts:
      dialTimeout: '10s'

    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
